services:
  mlops-git-workflow:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mlops-git-workflow
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
    working_dir: /workspace
    environment:
      - MLOPS_PROJECT_ROOT=/workspace
      - TEST_MODE=true
      - WSL_DISTRO_NAME=Ubuntu
      - PYTHONPATH=/workspace
      # TMDB API 설정
      - TMDB_API_KEY=88a297cdbe780782194a5cc6a9d86ec1
      - TMDB_REGION=KR
      - TMDB_LANGUAGE=ko-KR
      - TMDB_REQUEST_DELAY=0.25
      - TMDB_MAX_RETRIES=3
      - TMDB_TIMEOUT=30
      # 로깅 설정
      - LOG_LEVEL=INFO
      - LOG_FILE_PATH=logs/app.log
      - LOG_MAX_BYTES=10485760
      - LOG_BACKUP_COUNT=5
      # 데이터 설정
      - DATA_DIR=data
      - RAW_DATA_DIR=data/raw
      - PROCESSED_DATA_DIR=data/processed
      - BACKUP_DIR=data/backup
      - MAX_FILE_AGE_DAYS=30
      - COMPRESSION_ENABLED=true
    networks:
      - mlops-network
    stdin_open: true
    tty: true

networks:
  mlops-network:
    external: true
