version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ../models:/app/models
      - ../logs:/app/logs

  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns
      - ../mlartifacts:/mlartifacts
    command: >
      bash -c "pip install mlflow &&
               mlflow server --host 0.0.0.0 --port 5000 
               --backend-store-uri sqlite:///mlruns/mlflow.db
               --default-artifact-root /mlartifacts"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlruns/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlartifacts

volumes:
  mlruns:
  mlartifacts:
