# ==============================================================================
# Docker Compose - FastAPI 서비스
# WSL Docker 환경용
# ==============================================================================

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.api
      args:
        - PYTHON_VERSION=3.11
    image: ${API_IMAGE_NAME:-movie-mlops/api}:${API_VERSION:-latest}
    container_name: movie-mlops-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # FastAPI 설정
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=8000
      - API_WORKERS=${API_WORKERS:-4}
      - API_RELOAD=${API_RELOAD:-true}
      - API_LOG_LEVEL=${API_LOG_LEVEL:-info}
      
      # 환경 설정
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # 데이터베이스 연결
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/${POSTGRES_DB:-postgres}
      
      # Redis 연결
      - REDIS_URL=redis://redis:6379/${REDIS_DB:-0}
      
      # 외부 API
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=${TMDB_BASE_URL:-https://api.themoviedb.org/3}
      
      # 로깅
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    volumes:
      # 소스 코드 마운트 (개발 시 핫 리로드용)
      - ${HOST_PROJECT_PATH:-/mnt/c/dev/movie-mlops}/src:/app/src
      - ${HOST_PROJECT_PATH:-/mnt/c/dev/movie-mlops}/config:/app/config
      # 로그 폴더
      - ./logs/api:/app/logs
    networks:
      - movie-mlops-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: ${API_MEMORY_LIMIT:-1g}

networks:
  movie-mlops-network:
    external: true
