# ==============================================================================
# Docker Compose - Jupyter Notebook 개발 환경 (수정버전)
# WSL Docker 환경용 - 빌드 없이 기존 이미지 사용
# ==============================================================================

services:
  jupyter:
    image: jupyter/datascience-notebook:python-3.11
    container_name: movie-mlops-jupyter
    restart: unless-stopped
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-movie-mlops-jupyter}
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes
      - NB_UID=1000
      - NB_GID=1000
    volumes:
      # 프로젝트 전체를 작업 디렉토리로 마운트
      - ..:/home/jovyan/work
      # Jupyter 노트북 전용 폴더
      - ../notebooks:/home/jovyan/notebooks
      # 데이터 폴더
      - ../data:/home/jovyan/data
      # 모델 폴더  
      - ../models:/home/jovyan/models
    working_dir: /home/jovyan/work
    networks:
      - movie-mlops-network
    user: root
    command: >
      bash -c "
        echo 'Installing requirements...' &&
        if [ -f work/requirements/jupyter.txt ]; then
          pip install --no-cache-dir -r work/requirements/jupyter.txt || echo 'jupyter.txt not found, skipping';
        fi &&
        if [ -f work/requirements/base.txt ]; then
          pip install --no-cache-dir -r work/requirements/base.txt || echo 'base.txt not found, skipping';
        fi &&
        echo 'Starting Jupyter Lab...' &&
        start-notebook.sh 
        --NotebookApp.token='${JUPYTER_TOKEN:-movie-mlops-jupyter}'
        --NotebookApp.password=''
        --NotebookApp.allow_root=True
        --NotebookApp.ip='0.0.0.0'
        --NotebookApp.port=8888
        --NotebookApp.notebook_dir='/home/jovyan'
        --LabApp.default_url='/lab'
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  movie-mlops-network:
    external: true
