# ==============================================================================
# Docker Compose - Redis 캐시 서비스
# WSL Docker 환경용
# ==============================================================================

services:
  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    container_name: movie-mlops-redis
    restart: unless-stopped
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec
      --maxmemory ${REDIS_MEMORY_LIMIT:-512m}
      --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./logs/redis:/var/log/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - movie-mlops-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: ${REDIS_MEMORY_LIMIT:-512m}

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: movie-mlops-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - movie-mlops-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local

networks:
  movie-mlops-network:
    external: true
