global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@mlops-imdb.local'
  resolve_timeout: 5m

# Email templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing rules
route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    
    # API-specific alerts
    - match:
        service: api
      receiver: 'api-team'
      group_interval: 2m
    
    # Model-specific alerts
    - match:
        service: model
      receiver: 'ml-team'
    
    # System alerts
    - match:
        service: system
      receiver: 'devops-team'

# Alert receivers
receivers:
  # Default webhook (for development)
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:8001/alertmanager-webhook'
        send_resolved: true

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#mlops-critical'
        title: '🚨 Critical MLOps Alert'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          {{ end }}
        send_resolved: true
    
    # Email notification for critical alerts
    email_configs:
      - to: 'team@mlops-imdb.com'
        subject: '🚨 Critical MLOps Alert - {{ .GroupLabels.alertname }}'
        html: |
          <h2>Critical Alert Triggered</h2>
          {{ range .Alerts }}
          <h3>{{ .Annotations.summary }}</h3>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Service:</strong> {{ .Labels.service }}</p>
          <p><strong>Started:</strong> {{ .StartsAt }}</p>
          {{ end }}

  # API team notifications
  - name: 'api-team'
    slack_configs:
      - api_url: 'YOUR_API_TEAM_SLACK_WEBHOOK'
        channel: '#api-alerts'
        title: '🔧 API Alert'
        text: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Service:** {{ .Labels.service }}
          **Details:** {{ .Annotations.description }}
          {{ end }}

  # ML team notifications
  - name: 'ml-team'
    slack_configs:
      - api_url: 'YOUR_ML_TEAM_SLACK_WEBHOOK'
        channel: '#ml-alerts'
        title: '🤖 Model Alert'
        text: |
          {{ range .Alerts }}
          **Model Alert:** {{ .Annotations.summary }}
          **Details:** {{ .Annotations.description }}
          {{ end }}

  # DevOps team notifications
  - name: 'devops-team'
    slack_configs:
      - api_url: 'YOUR_DEVOPS_SLACK_WEBHOOK'
        channel: '#infrastructure'
        title: '🖥️ System Alert'
        text: |
          {{ range .Alerts }}
          **System Alert:** {{ .Annotations.summary }}
          **Instance:** {{ .Labels.instance }}
          **Details:** {{ .Annotations.description }}
          {{ end }}

# Inhibition rules (prevent spam)
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  # Inhibit API alerts if API is down
  - source_match:
      alertname: 'MLOpsAPIDown'
    target_match_re:
      alertname: 'API.*'