version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  app_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app/application.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  data_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/data/data_pipeline.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  data_processing:
    level: INFO
    handlers: [console, app_file, data_file]
    propagate: false

  tmdb_api:
    level: INFO
    handlers: [console, data_file]
    propagate: false

root:
  level: INFO
  handlers: [console, app_file, error_file]
